services:
  db:
    image: mysql:8.0
    container_name: edifis-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=edifis
      - MYSQL_DATABASE=edifis_pro
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: node:20-bookworm-slim
    container_name: edifis-backend
    working_dir: /app/backend
    volumes:
      - ./:/app
      - /app/backend/node_modules
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=edifis
      - DB_NAME=edifis_pro
      - DB_DIALECT=mysql
      - JWT_SECRET=super_secret_dev
      - JWT_EXPIRES_IN=1h
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm ci && npm start"

  frontend:
    image: node:20-bookworm-slim
    container_name: edifis-frontend
    working_dir: /app/frontend/edifis-pro
    volumes:
      - ./:/app
      - /app/frontend/edifis-pro/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      backend:
        condition: service_started
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"

volumes:
  db_data:
