services:
  db:
    image: mysql:8.0
    container_name: edifis-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=edifis
      - MYSQL_DATABASE=edifis_pro
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: node:20-bookworm-slim
    container_name: edifis-backend
    working_dir: /app/backend
    volumes:
      - ./:/app
      - /app/backend/node_modules
    ports:
      - '5000:5000'
    environment:
      - PORT=process.env.BACK_DOCK_PORT
      - NODE_ENV=process.env.NODE_ENV_DOCK
      - DB_HOST=process.env.DB_HOST_DOCK
      - DB_PORT=process.env.DB_PORT_DOCK
      - DB_USER=process.env.DB_USER_DOCK
      - DB_PASSWORD=process.env.DB_PASSWORD_DOCK
      - DB_NAME=process.env.DB_NAME_DOCK
      - DB_DIALECT=process.env.DB_DIALECT_DOCK
      - JWT_SECRET=process.env.JWT_SECRET_DOCK
      - JWT_EXPIRES_IN=process.env.JWT_EXPIRES_IN_DOCK
      - FRONTEND_URL=process.env.FRONTEND_URL_DOCK
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm ci && node scripts/seed.js && npm start"

  frontend:
    image: node:20-bookworm-slim
    container_name: edifis-frontend
    working_dir: /app/frontend/edifis-pro
    volumes:
      - ./:/app
      - /app/frontend/edifis-pro/node_modules
    ports:
      - '5174:5174'
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      backend:
        condition: service_started
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5174"

volumes:
  db_data:
