version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - '${BACKEND_PORT}:3000'
    environment:
      - DB_HOST=mariadb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./frontend/edifis-pro
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_DOCK}
      MYSQL_DATABASE: ${DB_NAME_DOCK}
    ports:
      - '${DB_PORT_DOCK}:3306'
