# Version de Docker Compose
version: '3.9'
# Définition des services
# Chaque service correspond à un conteneur Docker
services:
  # Service pour la base de données PostgreSQL
  backend:
    # Service pour l'API backend
    build: ./backend
    # Configuration des ports
    ports:
      - '${BACKEND_PORT}:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend/edifis-pro
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_DOCK}
      MYSQL_DATABASE: ${DB_NAME_DOCK}
    ports:
      - '${DB_PORT_DOCK}:3306'
