# ✅ Définir les redirections SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Ajouter des headers (dont CSP)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval';"
