name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Login Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login ACR
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 4. Build & Push frontend
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/edifis-frontend:latest ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/edifis-frontend:latest

      # 5. Build & Push backend
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/edifis-backend:latest ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/edifis-backend:latest

      # 6. Déploiement App Service
      - name: Deploy frontend container
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'edifis-frontend'
          images: ${{ secrets.ACR_LOGIN_SERVER }}/edifis-frontend:latest

      - name: Deploy backend container
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'edifis-backend'
          images: ${{ secrets.ACR_LOGIN_SERVER }}/edifis-backend:latest
